import express from 'express';
import StaticPage from '../models/StaticPage.js';

const router = express.Router();

// Get all static pages
router.get('/', async (req, res) => {
  try {
    const { isActive, showInFooter, search } = req.query;
    let query = {};
    
    // Add filters if provided
    if (isActive === 'true') {
      query.isActive = true;
    }
    
    if (showInFooter === 'true') {
      query.showInFooter = true;
    }
    
    let pages;
    
    if (search) {
      // Text search
      pages = await StaticPage.searchByText(search);
    } else {
      // Regular query with sorting
      pages = await StaticPage.find(query)
        .sort({ sortOrder: 1, createdAt: -1 });
    }
    
    console.log(`✅ Found ${pages.length} static pages`);
    
    res.json(pages);
  } catch (error) {
    console.error('❌ Error fetching static pages:', error);
    res.status(500).json({ 
      error: 'Internal server error',
      message: error.message 
    });
  }
});

// Get static page by ID or slug
router.get('/:identifier', async (req, res) => {
  try {
    const { identifier } = req.params;
    let page = null;
    
    console.log('📄 Fetching static page by identifier:', identifier);
    
    // Try to get by ID first (if it's a number)
    if (!isNaN(identifier)) {
      page = await StaticPage.findOne({ id: parseInt(identifier) });
    }
    
    // If not found by ID, try by slug
    if (!page) {
      page = await StaticPage.findBySlug(identifier);
    }
    
    if (!page) {
      return res.status(404).json({ error: 'Static page not found' });
    }
    
    // Increment view count
    await page.incrementViewCount();
    
    console.log('✅ Found static page:', page.title);
    
    res.json(page);
  } catch (error) {
    console.error('❌ Error deleting static page:', error);
    console.error('❌ Error details:', {
      name: error.name,
      message: error.message,
      code: error.code
    });
    res.status(500).json({ 
      error: 'Internal server error',
      message: error.message 
    });
  }
});

// Create new static page
router.post('/', async (req, res) => {
  console.log('🔥 POST request received for static pages');
  try {
    const pageData = req.body;
    
    console.log('📄 Creating new static page:', pageData?.title || 'NO TITLE');
    console.log('📄 Received page data:', JSON.stringify(pageData, null, 2));
    console.log('🔍 Checking database connection...');
    
    // Validate required fields
    if (!pageData.title || !pageData.content) {
      return res.status(400).json({ 
        error: 'Missing required fields: title, content' 
      });
    }
    
    // Check for unwanted console messages in content
    if (pageData.content.includes('Download the React DevTools') || 
        pageData.content.includes('React Router Future Flag Warning') ||
        pageData.content.includes('react-router-dom.js')) {
      console.warn('🚫 Rejected content with console messages');
      return res.status(400).json({ 
        error: 'Invalid content: contains system messages' 
      });
    }
    
    console.log('✅ Content validation passed');
    
    // Check if slug already exists (if provided)
    console.log('🔍 Checking for existing slug:', pageData.slug);
    if (pageData.slug) {
      const existingPage = await StaticPage.findOne({ slug: pageData.slug });
      console.log('🔍 Existing page found:', existingPage ? 'YES' : 'NO');
      if (existingPage) {
        return res.status(400).json({ 
          error: 'A page with this slug already exists' 
        });
      }
    }
    
    // Create new page (ID will be auto-generated by pre-save middleware)
    console.log('🔄 Creating new StaticPage instance...');
    const newPage = new StaticPage({
      ...pageData,
      isActive: pageData.isActive !== undefined ? pageData.isActive : true,
      showInFooter: pageData.showInFooter !== undefined ? pageData.showInFooter : false
    });
    
    console.log('💾 Attempting to save page...');
    const savedPage = await newPage.save();
    
    console.log('✅ Static page created successfully:', savedPage.id);
    console.log('📤 Sending response with status 201');
    
    res.status(201).json(savedPage);
  } catch (error) {
    console.error('❌ Error creating static page:', error);
    console.error('❌ Error stack:', error.stack);
    console.error('❌ Error details:', {
      name: error.name,
      message: error.message,
      code: error.code
    });
    
    // Handle duplicate key error
    if (error.code === 11000) {
      const field = Object.keys(error.keyPattern)[0];
      return res.status(400).json({ 
        error: `A page with this ${field} already exists` 
      });
    }
    
    res.status(500).json({ 
      error: 'Internal server error',
      message: error.message 
    });
  }
});

// Update static page
router.put('/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const pageData = req.body;
    
    console.log('📄 Updating static page:', id);
    
    // Find page by ID (number)
    const page = await StaticPage.findOne({ id: parseInt(id) });
    
    if (!page) {
      return res.status(404).json({ error: 'Static page not found' });
    }
    
    // If slug is being updated, check if it already exists
    if (pageData.slug && pageData.slug !== page.slug) {
      const existingPage = await StaticPage.findOne({ slug: pageData.slug });
      if (existingPage) {
        return res.status(400).json({ 
          error: 'A page with this slug already exists' 
        });
      }
    }
    
    // Update page
    Object.assign(page, pageData);
    const updatedPage = await page.save();
    
    console.log('✅ Static page updated successfully:', id);
    
    res.json(updatedPage);
  } catch (error) {
    console.error('❌ Error updating static page:', error);
    
    // Handle duplicate key error
    if (error.code === 11000) {
      const field = Object.keys(error.keyPattern)[0];
      return res.status(400).json({ 
        error: `A page with this ${field} already exists` 
      });
    }
    
    res.status(500).json({ 
      error: 'Internal server error',
      message: error.message 
    });
  }
});

// Delete static page
router.delete('/:id', async (req, res) => {
  try {
    const { id } = req.params;
    
    console.log('📄 Deleting static page:', id);
    
    // Find and delete page by ID (number)
    const page = await StaticPage.findOneAndDelete({ id: parseInt(id) });
    
    if (!page) {
      return res.status(404).json({ error: 'Static page not found' });
    }
    
    console.log('✅ Static page deleted successfully:', id);
    
    res.json({ message: 'Static page deleted successfully' });
  } catch (error) {
    console.error('❌ Error creating static page:', error);
    console.error('❌ Error stack:', error.stack);
    res.status(500).json({ 
      error: 'Internal server error',
      message: error.message 
    });
  }
});

// Get footer pages (public endpoint)
router.get('/public/footer', async (req, res) => {
  try {
    console.log('📄 Fetching footer pages');
    
    const footerPages = await StaticPage.findFooterPages();
    
    console.log(`✅ Found ${footerPages.length} footer pages`);
    
    res.json(footerPages);
  } catch (error) {
    console.error('❌ Error fetching footer pages:', error);
    res.status(500).json({ 
      error: 'Internal server error',
      message: error.message 
    });
  }
});

// Toggle page status
router.patch('/:id/toggle-status', async (req, res) => {
  try {
    const { id } = req.params;
    
    console.log('📄 Toggling status for static page:', id);
    
    const page = await StaticPage.findOne({ id: parseInt(id) });
    
    if (!page) {
      return res.status(404).json({ error: 'Static page not found' });
    }
    
    page.isActive = !page.isActive;
    const updatedPage = await page.save();
    
    console.log('✅ Static page status toggled successfully:', id);
    
    res.json(updatedPage);
  } catch (error) {
    console.error('❌ Error toggling static page status:', error);
    res.status(500).json({ 
      error: 'Internal server error',
      message: error.message 
    });
  }
});

// Toggle footer visibility
router.patch('/:id/toggle-footer', async (req, res) => {
  try {
    const { id } = req.params;
    
    console.log('📄 Toggling footer visibility for static page:', id);
    
    const page = await StaticPage.findOne({ id: parseInt(id) });
    
    if (!page) {
      return res.status(404).json({ error: 'Static page not found' });
    }
    
    page.showInFooter = !page.showInFooter;
    const updatedPage = await page.save();
    
    console.log('✅ Static page footer visibility toggled successfully:', id);
    
    res.json(updatedPage);
  } catch (error) {
    console.error('❌ Error toggling static page footer visibility:', error);
    res.status(500).json({ 
      error: 'Internal server error',
      message: error.message 
    });
  }
});

export default router;